name: Create zip with selected files

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create folder with selected files
        run: |
          mkdir mastro
          cp -r GNodes mastro/
          cp -r Handlers mastro/
          cp -r Icons mastro/
          cp -r Operators mastro/
          cp -r UI mastro/
          cp -r Utils mastro/
          cp -r *.py mastro/
          cp mastro.blend mastro/
          cp LICENSE.txt mastro/
          cp blender_manifest.toml mastro/

      - name: Create ZIP file
        run: |
          cd mastro
          zip -r ../mastro.zip .
          
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-mastro
          name: MaStro ZIP
          files: mastro.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
